### ISSUE TITLE
Non-Windows-1252 translations of EU4

### ISSUE THREAD

**Issue by IohannesIohannium** [ParadoxGameConverters/EU4toVic2#137]
A similar problem of #148, the [EDIT]EU4 Polish translation uses Windows-1250 coding, mojibake'd as Windows-1252. The solution would be the converter to still use Windows-1252 mojibake and a little edit on Vic2 fonts (probably added as a faq to download).

[Polish fonts.zip](https://github.com/Idhrendur/paradoxGameConverters/files/1808170/gfx.zip)

A similar problem (Windows-1250/"Central Europe") may be encountered with Czech, Slovak, Hungarian, Slovene, Serbo-Croatian, Romanian, and Albanian translations, yet I have no solution for such as the edit only supports Polish edit.

**Comment by Zemurin** [comment]
We have expanded on this where we could. All dynamically generated content (countries, adjectives, parties) uses all available sources of localization strings and merges them together in our outputs, and for missing fields we paste english localization.

However vanilla translations cannot be in our scope, several mods already exist that deal with these and carry their own fonts, as described in FAQ. Only one version of these fonts can be active at a time anyway and we cannot tell Vic2 which font to use - one has to override default ones. 

I'm closing this issue since it was fixed to the best of out ability and to the extent of our responsibility.
