### ISSUE TITLE
War and rebel conversion

### ISSUE THREAD

**Issue by IohannesIohannium** [ParadoxGameConverters/EU4toVic2#152]
Currently, EU4Vic2 doesn't convert any rebellion or conflict.

The first could still be done by using /history/units/REB_oob.txt, creating each rebel regiment, although very poorly and not ensuring they'd be rising for the same faction as before.

Any occupied province can still be set as occupied at game start, just by changing who's the controller in the relevant province history file (usually line 2, controller = [TAG]).

War conversion, instead, would require the creation of a .txt file in /history/wars, using the following format:
```
[war start in yyyy.mm.dd] = {
	add_attacker = [any attacker tag, one line each]
	add_defender = [any defender tag, one line each]
	
	war_goal = {
		casus_belli = [a casus belli]
		actor = [attacker war leader]
		receiver = [defender war leader]
	}

}
```

Yet, as casi belli vary from EU4 to Vic2, it'd be necessary to provide mappings for them, either from code or from a data file, this latter working with a syntax similar to `EU4 = cb_restore_personal_union Vic2 = make_puppet`

**Comment by Zemurin** [comment]
There is no "unrest" in provinces, it's a secondary value updated on the fly. Without it we cannot estimate militancy to be applied to particular pops.

Rebel factions are **always** active, and operate over a set of provinces. When unrest in those provinces rises over 0, uprising progress is stored within the rebel faction (0.00-100.00). However, until rebels pop with armies, the faction is flagged as "active=no", so we cannot determine which factions are actually causing unrest unless they have progress higher than 0. Even then, we do not know the extent of their militancy as we can't see what's feeding the unrest progress.

Once they spawn armies, we cannot easily access them as they're within REB={} country entry, which we ignore for a good reason. Implementing a special parser for REB wouldn't help much due to the fact rebels in Vic2 don't feed from soldiers but from every pop type marked with rebel flag. This would require special functions for spawning rebel armies that would mirror regular army spawn process.

Even then, with regular armies, we know whom they belong to and what province feeds them. Rebel armies can call multiple vic2 provinces home (due to nature of N-to-M country mapping), and those provinces may in fact belong to different vic2 countries, further complicating things.

I'm closing this request as unfeasible.
