### ISSUE TITLE
Dharma governments

### ISSUE THREAD

**Issue by IohannesIohannium** [ParadoxGameConverters/EU4toVic2#165]
It seems that in EU4 saves since Dharma a country history will feature this, regardless of using the DLC or not:

```
	NOV={
		government_rank=1
		government_name="russian_republic"
		subject_focus=0
		...
```
The government_name field could be used to determine what to map in saves that show to be of at least 1.26 version

**Comment by Zemurin** [comment]
While assigning governments from government_name is straightforward, naming them might not be.

Let's roll England through some fun times:
```
	ENG={
		government_name="default_monarchy" 
		government={
			government="monarchy"
			reform_stack={
				reforms={
					"monarchy_mechanic"
					"english_monarchy"
```
Reform into republic (noble elite):
```
	ENG={
		government_name="noble_republic" 
		government={
			government="republic"
			reform_stack={
				reforms={
					"republic_mechanic"
					"noble_elite_reform"
```
Reform into theocracy (monastic order):
```
	ENG={
		government_name="gov_religious_order" 
		government={
			government="theocracy"
			reform_stack={
				reforms={
					"theocracy_mechanic"
					"monastic_order_reform"
```
And back into monarchy:
```
	ENG={
		government_name="default_monarchy" 
		government={
			government="monarchy"
			reform_stack={
				reforms={
					"monarchy_mechanic"
					"feudalism_reform"
```
Correlate with zz_default_government_names.txt since there is no actual "default_monarchy":
```
default_monarchy = {
	rank = {
		1 = DUCHY
		2 = KINGDOM
		3 = EMPIRE
	}
```
Into localisation/government_names_l_english.yml:
```
 DUCHY:0 "Duchy"
 KINGDOM:0 "Kingdom"
 EMPIRE:0 "Empire"
```
Prefix is at localisation/countries_l_english.yml:
` ENG_ADJ:0 "English"`

Thus we can construct "**English Kingdom**" or "**English Empire**" but this is hardly a _government name_! 

Roll back to  zz_default_government_names.txt and look further:
```
default_monarchy = {
	trigger = {
		has_reform = monarchy_mechanic
	}
```

Locate what that is in localisation/government_l_english.txt:
` monarchy_mechanic:0 "Monarchy"
`

And we get an "**English Monarchy**" - good enough.

Onto republic:
Noble republic exists as a specific government reform in localisation/text_l_english.yml:
` noble_republic:0 "Noble Republic"
`

Uh, "**English Noble Republic**"? I've seen worse things.

Monastic order phase:
In common/government_names/01_government_names.txt skip straight to the trigger:
```
gov_religious_order = {
	trigger = {
		has_reform = monastic_order_reform
	}
```
Also in localisation/government_l_english.txt:
`  monastic_order_reform:0 "Monastic Order"
`

So, "**English Monastic Order**".

Finally, back onto monarchy but without english_monarchy reform, we again get English Monarchy, but with different political and social reforms, maybe an absolutist government.

**Comment by Zemurin** [comment]
resolved through moddable reforms file.
