### ISSUE TITLE
Startdate

### ISSUE THREAD

**Issue by IohannesIohannium** [ParadoxGameConverters/EU4toVic2#166]
The EU4 savegame always has the day the game has been ended. This could be used to determine when to make the "EU4 end game" bookmark start.

Files to edit are defines.lua (line 3) and common/bookmarks.txt (line 5)

**Comment by Zemurin** [comment]
My regular game has this inside the file:
start_date=1444.11.11
A 1356 mod started at 1420 bookmark has this:
start_date=1420.5.21

and finally, we're already grabbing save date from the savegame:
date=1421.1.18

In essence, while moving the eu4-end-date/v2-start-date is nice, moving eu4-start-date is more important since negatives affect cultural conversions. I'll see if I can address both.
