### ISSUE TITLE
Make the minority pops feature more powerful

### ISSUE THREAD

**Issue by Idhrendur** [ParadoxGameConverters/EU4toVic2#26]
https://forum.paradoxplaza.com/forum/index.php?threads/the-eu4-to-v2-converter-project.707362/page-177#post-20566491
https://forum.paradoxplaza.com/forum/index.php?threads/the-eu4-to-v2-converter-project.707362/page-178#post-20567717

**Comment by IohannesIohannium** [comment]
The minority feature of the converter is based upon the provided Vic2 province history files. The minoritypops simply tells the converter what ethnicities and religions should be copied straight-away from Vic2. (e.g. there are, let's say, 500 Ashkenazi Jews in Frankfurt, the minoritypops states to keep ashkenazis and jews: as a result, this group of 500 Ashkenazi Jews will always exist in Frankfurt, independently of whoever else is in that city, may they be Germans, Muslims or even other Ashkenazi)

**Comment by Idhrendur** [comment]
It's been almost four years (!) since I wrote that, but I think what I was proposing was taking the mechanism you just described so that the mappings specify both a culture to read from Vic2 and a culture to output to the mod. By having both the same, you get the current functionality. But if someone had a game with, say, Jewish pops ruling everything, then could change the output and have the converter generate minority Christians in place of minority Jews.

**Comment by IohannesIohannium** [comment]
Okay, now I have a good idea on how to solve this.
Our current syntax for the minority_pops.txt is the following:
`minority = { culture = ashkenazi religion = jewish }`
And this keeps all vanilla Vic2 Ashkenazi Jews were they are.
Now, I propose to expand it further:
`minority = { culture = ashkenazi religion = jewish newculture = north_german newreligion = protestant }`
All the vanilla Vic2 Ashkenazi Jews will remain where they are. But if the province they're in is owned by an Ashkenazi Jewish country, then these pops would become North German Protestants and become a minority again.

**Comment by Idhrendur** [comment]
I'd prefer ``alternate_culture`` and ``alternate_religion``. But I think overall that would work.

As an alternative, we could transform
``minority = { culture = ashkenazi religion = jewish }`` into
```minority = { culture = ashkenazi religion = jewish newculture = ashkenazi newreligion = jewish }```
It wouldn't automatically handle the case where the majority is ashkenazi jewish, but would allow for matching ashkenazi jewish in original Vic2 and making it a different kind of minority:
```minority = { culture = ashkenazi religion = jewish newculture = khazar newreligion = jewish }```

Shoot, we could even do both, if desired.

**Comment by Zemurin** [comment]
From converter perspective, this is just replacing every ashkenazi in a normal game with a khazar. So, khazars in europe, in americas, all around the world as minorities. Why khazar, one may ask. Not a clue.

I dislike this idea entirely, it adds nothing of value. For it to make sense you'd have to blanket the world with jewish provinces in ck2, and what's the point of such a game anyway? They'd all assimilate eventually.

**Comment by IohannesIohannium** [comment]
Also, we'd have to mod in a Khazar culture we don't have

**Comment by Idhrendur** [comment]
Well, khazars were just an illustrative example. But if I understand @Zemurin's objection correctly, he's right in that would affect Ashkenazi in New York just as much as ones in Poland. Which maybe makes sense, maybe not. The minority pops feature is kind of funny that way. And maybe good enough. Maybe the solution for the original request is to tell them to mod their mod by hand to get that level of detail.

**Comment by Zemurin** [comment]
My main concerns are this:

1. We're replacing minority A (jews, gypsies, mormons) with minorities B (khazari, germans and .. the french). This happens if jews in particular (since no other minorities exist in eu4) rule the provinces where they would normally appear as minorities.

2. Why Khazari, germans and ... the french? They make no sense (no matter what 3 you put in there), since all three might legitimately exist outside of jewish europe/americas. In fact, if poland is jewish, suddenly there are khazari in there, as well as in ukraine (replace name and location with any culture you decide to use).

3. These minorities are universal minorities because they make inherent sense no matter what happens in 15th century onwards. For another culture to be used as a minority we'd need to track since ck2 what cultures have gone extinct and use those. We can't do that unless we have access to ck2, and even then we'd have to compare ck2 mod against ck2 base which is a lot of work for practically no gain.

4. Furthermore, if jews own all europe then what's the point of minorities? All cultures that survive eu4 will still exist in all provinces as minorities due to cultural/religious conversion in eu4 never doing 
a 100%.

I say drop this idea.

**Comment by Idhrendur** [comment]
Sounds good. Feel free to close.
