### ISSUE TITLE
Odd culture conversions in colonies

### ISSUE THREAD

**Issue by Idhrendur** [ParadoxGameConverters/EU4toVic2#268]
Reported here: https://forum.paradoxplaza.com/forum/index.php?threads/eu4-to-vic2-converter-release-thread.973026/page-166#post-25861384
Mod and save here: https://forum.paradoxplaza.com/forum/index.php?threads/eu4-to-vic2-converter-release-thread.973026/page-166#post-25861396

**Comment by Zemurin** [comment]
This is an 17th Oct 1792 save of a game where player created a custom norwegian germanic nation of **Sundaland** at over existing south american clay recently (1690s) - some colonized, some not, resulting in a messy history. Sample example:

![borked](https://user-images.githubusercontent.com/2392697/71163964-6a092880-224e-11ea-8946-f556269c5bc2.png)

For example this province was supposed to be owned by someone else, but is not. 

Also since culture is converted 17 days prior to save date, there is no noticeable conversion.

Nothing to fix here, can close.
