### ISSUE TITLE
Iranian & Turanian new world culture names

### ISSUE THREAD

**Issue by MaxTheDesertManIran** [ParadoxGameConverters/EU4toVic2#307]
The converter currently uses a single culture for the colonial Turanian (Central Asian) and Iranian cultures of the new continents. I suggest splitting this into two distinct cultures inside Victoria's Iranian-Turanian culture group, with the following names:
![names](https://user-images.githubusercontent.com/34010166/70027871-6459e480-15b8-11ea-95a1-c26a3b393203.PNG)

- Eu4 Iranian : tajik, persian, saka, luri, khorasani, mazandarani, parthian, khuzi, lurish, persian, luri_colonial, tabari, scythian, sarmatian, iazyges, sogdian, tocharian, tajihk, east_persian, afghani, afghan, pashtun, kushan, baluchi, baloch, hazara, kurdish;

- Eu4 Turanian : qashqai, uzbek, uzbehk, karluk, khazak, kirgiz, kirghiz, old_kirgiz, uyghur, old_uyghur, turkmeni, tartar, bolghar, cuman, avar, khazar, astrakhani, bashkir, crimean, kazani, mishary, nogaybak, qasim, avar, chaghatai, mishar, nogai, tartar_colonial, hunnic, sinoturk;

This'd take a lot of work and is mostly aesthetic, so it's by no means a priority.

**Comment by Idhrendur** [comment]
I love this kind of feedback!

It's not too much work, actually. The biggest trick is adding the new cultures (or renaming Vic2 ones already in the converter). And it's only really a trick because appropriate names are needed. If you wanted to take a stab at that, they're defined in [cultures.txt](https://github.com/ParadoxGameConverters/EU4toVic2/blob/master/EU4toV2/Data_Files/blankMod/output/common/cultures.txt), with localisations in [0_Cultures.csv](https://github.com/ParadoxGameConverters/EU4toVic2/blob/master/EU4toV2/Data_Files/blankMod/output/localisation/0_Cultures.csv). It looks like the converter adds dinajidad, janub, saahi, and gypsy. It also looks like some last names were researched for the existing cultures, but only noted, not fully added. I'm not sure what to make of them. Finally, Persia was made a union nation for the Persian culture. It seems like this is a cultural group you know about, so I'd gladly take any improvements you could make.

Once that's done, the culture mappings rules in [cultureMap.txt](https://github.com/ParadoxGameConverters/EU4toVic2/blob/master/EU4toV2/Data_Files/cultureMap.txt) and optionally [slaveCultureMap.txt](https://github.com/ParadoxGameConverters/EU4toVic2/blob/master/EU4toV2/Data_Files/slaveCultureMap.txt) would need updating.

**Comment by IohannesIohannium** [comment]
This is a really good idea and, to be fair, I would mod it in as soon as possible.
