### ISSUE TITLE
Allow development to affect pops

### ISSUE THREAD

**Issue by Idhrendur** [ParadoxGameConverters/EU4toVic2#31]
https://forum.paradoxplaza.com/forum/index.php?threads/the-eu4-to-v2-converter-project.707362/page-147#post-19835132
https://forum.paradoxplaza.com/forum/index.php?threads/the-eu4-to-v2-converter-project.707362/page-147#post-19835355
https://forum.paradoxplaza.com/forum/index.php?threads/the-eu4-to-v2-converter-project.707362/page-154#post-19976429
https://forum.paradoxplaza.com/forum/index.php?threads/the-eu4-to-v2-converter-project.707362/page-154#post-19976602
https://forum.paradoxplaza.com/forum/index.php?threads/the-eu4-to-v2-converter-project.707362/page-159#post-20127741
https://forum.paradoxplaza.com/forum/index.php?threads/the-eu4-to-v2-converter-project.707362/page-159#post-20129497
https://forum.paradoxplaza.com/forum/index.php?threads/the-eu4-to-v2-converter-project.707362/page-159#post-20137258

**Comment by Zemurin** [comment]
The below only applies to pop shaping which is a problem I would like to fix very much:

Argument that we can take total development of the world, modified by buildings, trade goods, province modifiers, life rating etc, and then determine "population per modified dev point" is wrong. What currently happens with pop shaping on is that a billion people migrate from Asia to Europe since it has better dev and liferating per province, on average, among other factors. As a result we have a Madrid province with 1.2M people and a Gibraltar with almost 100k (up from original 3k).

Also, the argument that we must take vanilla Vic2 population, and then redistribute it according to some key is also wrong - vanilla starting Vic2 population makes sense only in vanilla Vic2 history, and, mind you - not even in eu4-to-vic2 conversions. Different development, different wars, or plagues over those 4 centuries would result in a different total population. Also, EU4 history files alter only a small handful of provinces over time, so for example, one Madrid, Florence or Rome is effectively identical in 1444 and 1821.

To resolve this, and to keep **the player satisfied and rewarded** for their work, population boosting should indeed occur according to dev investment (ie. playing tall), but again within the limits of reason.

I propose a relatively simple-to-comprehend formula; boost population upwards according to dev investment directly (1 dev investment = 1% population rise), modified by (liferating - 30), so those nice european 35 LR provinces can get 1.05% per dev point, while tundras and deserts get 0.85% per development.

As a result, already large european provinces will get proportionally smaller boosts per mana investiture; a 60-dev Ulm will gain some 40%ish population more on game start but that's it, where a 3-dev fertile plains boosted to 53 dev would get 50%, assuming life rating 30.

This method:
1) keeps population where they are, simply adjusting the numbers to represent land investments over centuries (mana either goes to war or to development; if latter then the history is less devastating than RL history)
2) rewards tall players but an investment to get /double/ population is insane as it requires going well over 100 dev per province.

Please comment.

**Comment by Idhrendur** [comment]
Something like that is the ideal, I think. Maybe initially make it an option, and if it works well it can become the default. Maybe replace the default.
