### ISSUE TITLE
Improve cores/decision for formable nations

### ISSUE THREAD

**Issue by Idhrendur** [ParadoxGameConverters/EU4toVic2#44]
https://forum.paradoxplaza.com/forum/index.php?threads/the-eu4-to-v2-converter-project.707362/page-185#post-20647220
https://forum.paradoxplaza.com/forum/index.php?threads/the-eu4-to-v2-converter-project.707362/page-185#post-20647246
https://forum.paradoxplaza.com/forum/index.php?threads/the-eu4-to-v2-converter-project.707362/page-185#post-20648217
https://forum.paradoxplaza.com/forum/index.php?threads/the-eu4-to-v2-converter-project.707362/page-185#post-20650154
https://forum.paradoxplaza.com/forum/index.php?threads/the-eu4-to-v2-converter-project.707362/page-185#post-20652188
https://forum.paradoxplaza.com/forum/index.php?threads/the-eu4-to-v2-converter-project.707362/page-186#post-20674898

**Comment by Zemurin** [comment]
1. Issue One: Cores
This whole issue is backwards. Using North German/German and Riga as examples.

We know EU4's Prussian, Saxon, Pomeranian etc. are native to europe_superregion and easterneurope_superregion. Riga is within those superregions. They will not mutate as neither of those superregions are outside base supergroup ("oldworld_supergroup"), so the dynamic culture generation is not applicable.

Since we're not firing up neocultures, we rely on base mappings in culture_map.txt. Mappings say all of these cultures map into V2's north_german, inside german culturegroup.

Only now we can assign cultural cores and culturegroup cores. 

We're assigning these in provinces where these cultures have majority. Riga will certainly be one of them as it contains 100% north_german population since 1444. 

How exactly would we discern it being "unneeded"? We don't track cultures by regions, only superregions - even if it did, Riga would still track as being a core german province since it has 100% german population. 

Also, creating a manual config file that would limit cultural cores for cultures to within bounds of specific eu4 regions is *very* railroady and makes no sense in a world that's divorced from reality since CK2 - Imagine germans only get german cores in north and south germany + austria, when since 1158 the entire HRE has shifted into france as a result of mongols occupying germany and HRE has since converted the majority of population in france to german, all before EU4 even got started.

So this approach is a no-go and should be changed at this stage. Converter has separate options to disable generation of cultural and culturegroup cores if those cause issues.

2. Issue Two - culturegroup cores outside superregion.
To form a cultural union, one needs to control all culturegroup cores, not all provinces containing the majority of same-group cultures. We're not generating culturegroup cores in colonies by default. For conquered land outside home superregion we're also not assigning cores since the culture there will mutate into a neoculture and neocultures are not present within unions.txt.

It will never be required to conquer vinlander USA as Sweden to form scandinavia, but if baltics have been danish since 940, yes, they will be required.

3. Issue Three - Decisions
*form_union_nation* is the base decision for any cultural unification, unless overridden for flavor. It requires one to either own all culturegroup cores or have their owners sphered. If the owner is a vassal, it must be our vassal. As a result it will get integrated. No change needed here either.

I'm closing this issue until such a time a workable proposal for improvement is suggested, but at the moment I believe current solutions are working fine.
