### ISSUE TITLE
Support cyrillic in place names

### ISSUE THREAD

**Issue by Idhrendur** [ParadoxGameConverters/EU4toVic2#49]
https://forum.paradoxplaza.com/forum/index.php?threads/the-eu4-to-v2-converter-project.707362/page-190#post-20815795
https://forum.paradoxplaza.com/forum/index.php?threads/the-eu4-to-v2-converter-project.707362/page-191#post-20818725

**Comment by Zemurin** [comment]
Similar to issue #137 and marginally related to #140

We cannot internally handle anything non-ansi based as our current parser cannot deal with mojibake. It could theoretically read the strings in original codepage but not when mixed with other localizations in the same file, as is required by vic2.
This issue is further rendered moot by the requirement to use russian-modded fonts that would override vanilla fonts, so we cannot copy them over. It is user responsibility to use their own localization mod along with converter output.

I'm closing this as nonviable.
