### ISSUE TITLE
Clean up the mappers used by V2Flag

### ISSUE THREAD

**Issue by Idhrendur** [ParadoxGameConverters/EU4toVic2#56]
The entire thing is confusing and seems confused. It needs a good cleanup.

**Comment by Zemurin** [comment]
Mappers themself have been rewritten and work as well as any other. I've verified the algorithm in Flag.cpp and after fixing a few kinks it's now producing correct colonial, custom and regular flags. Trouble is it's divorced from naming mappers (because country mappers use one set of inputs and this uses actual flags on disk as source), which makes it appear confusing, but it's solid for now.

Replacing targa with something that can chew on UTF8 filepaths is another issue entirely and not really a fault of V2Flag.
